# Project 5: Working with Pandas and SQL Databases (Movies Dataset)

## Creating an SQLite Database

1. __Import__ sqlite3 (as sq3) and __create__ a new SQLite Database with the name __"movies.db"__.

In [1]:
import sqlite3 as sq3

In [2]:
con = sq3.connect("movies.db")

In [3]:
con

In [4]:
con.execute("Select * FROM sqlite_master").fetchall()

[]

In [5]:
con.close()

## Loading Data from DataFrames into an SQLite Database

2. __Load__ the json file __"some_movies.json"__ and __split__ the dataset into the following __four datasets__ (save each dataset in a Pandas DataFrame).

In [6]:
import pandas as pd
import json

In [7]:
with open("some_movies.json") as f:
    data = json.load(f)

In [9]:
df = pd.json_normalize(data, sep = "_")

In [11]:
df.head()

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,tagline,title,video,vote_average,vote_count,belongs_to_collection_id,belongs_to_collection_name,belongs_to_collection_poster_path,belongs_to_collection_backdrop_path,belongs_to_collection
0,False,/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg,356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,en,Avengers: Endgame,After the devastating events of Avengers: Infi...,...,Part of the journey is the end.,Avengers: Endgame,False,8.3,12607,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
1,False,/wcC7kCICL6x6zHUlUyNp9pWoqW1.jpg,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",...,Enter the World of Pandora.,Avatar,False,7.4,21000,87096.0,Avatar Collection,/nslJVsO58Etqkk17oXMuVK4gNOF.jpg,/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg,NaN
2,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,...,Every generation has a story.,Star Wars: The Force Awakens,False,7.4,14205,10.0,Star Wars Collection,/r8Ph5MYXL04Qzu4QBbq2KjqwtkQ.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
3,False,/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,en,Avengers: Infinity War,As the Avengers and their allies have continue...,...,An entire universe. Once and for all.,Avengers: Infinity War,False,8.3,17718,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
4,False,/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",,597,tt0120338,en,Titanic,101-year-old Rose DeWitt Bukater tells the sto...,...,Nothing on Earth could come between them.,Titanic,False,7.8,16661,NaN,NaN,NaN,NaN,NaN

__Dataset #1 (Movies)__ with columns ["id", "title", "revenue", "budget", "belongs_to_collection_name", "release_date"]. <br>
Convert "release_date" to datetime and transform "budget" and "revenue" to Million USD before loading into the Database.

In [12]:
movies = df[["id", "title", "revenue", "budget", "belongs_to_collection_name", "release_date"]].copy()
movies

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797800564,356000000,The Avengers Collection,2019-04-24
1,19995,Avatar,2787965087,237000000,Avatar Collection,2009-12-10
2,140607,Star Wars: The Force Awakens,2068223624,245000000,Star Wars Collection,2015-12-15
3,299536,Avengers: Infinity War,2046239637,300000000,The Avengers Collection,2018-04-25
4,597,Titanic,1845034188,200000000,NaN,1997-11-18
5,135397,Jurassic World,1671713208,150000000,Jurassic Park Collection,2015-06-06
6,420818,The Lion King,1656943394,260000000,NaN,2019-07-12
7,24428,The Avengers,1519557910,220000000,The Avengers Collection,2012-04-25
8,168259,Furious 7,1515047671,190000000,The Fast and the Furious Collection,2015-04-01
9,99861,Avengers: Age of Ultron,1405403694,250000000,The Avengers Collection,2015-04-22
10,284054,Black Panther,1346739107,200000000,Black Panther Collection,2018-02-13
11,12445,Harry Potter and the Deathly Hallows: Part 2,1341511219,125000000,Harry Potter Collection,2011-07-07
12,181808,Star Wars: The Last Jedi,1332539889,200000000,Star Wars Collection,2017-12-13
13,330457,Frozen II,1330764959,150000000,Frozen Collection,2019-11-20
14,351286,Jurassic World: Fallen Kingdom,1303459585,170000000,Jurassic Park Collection,2018-06-06
15,109445,Frozen,1274219009,150000000,Frozen Collection,2013-11-27
16,321612,Beauty and the Beast,1263521126,160000000,NaN,2017-03-16
17,260513,Incredibles 2,1241891456,200000000,The Incredibles Collection,2018-06-14

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          18 non-null     int64
 1   title                       18 non-null     object
 2   revenue                     18 non-null     int64
 3   budget                      18 non-null     int64
 4   belongs_to_collection_name  15 non-null     object
 5   release_date                18 non-null     object
dtypes: int64(3), object(3)
memory usage: 996.0+ bytes

In [14]:
movies.release_date = pd.to_datetime(df.release_date)

In [15]:
movies.revenue = df.revenue/1000000
movies.budget = df.budget/1000000

In [16]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          18 non-null     int64
 1   title                       18 non-null     object
 2   revenue                     18 non-null     float64
 3   budget                      18 non-null     float64
 4   belongs_to_collection_name  15 non-null     object
 5   release_date                18 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 996.0+ bytes

__Dataset #2 (Votes)__ with columns ["id", "vote_count", "vote_average"].

In [20]:
votes = df[['id', 'vote_count', 'vote_average']].copy()

In [21]:
votes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            18 non-null     int64
 1   vote_count    18 non-null     int64
 2   vote_average  18 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 564.0 bytes

__Dataset #3 (Genres)__ with columns ["genre_id", "genre_name", "id"]. <br>

In [24]:
genres = pd.json_normalize(data = data, record_path = "genres", meta = "id", record_prefix = "genre_")
genres.head()

   genre_id       genre_name      id
0        12        Adventure  299534
1       878  Science Fiction  299534
2        28           Action  299534
3        28           Action   19995
4        12        Adventure   19995

__Dataset #4 (Prod)__ with columns ["comp_id", "comp_logo_path", "comp_name", "comp_origin_country", "id" ]. <br>

In [25]:
prod = pd.json_normalize(data = data, record_path="production_companies", meta = "id", record_prefix= "comp_")
prod.head()

,comp_id,comp_logo_path,comp_name,comp_origin_country,id
0,420,/hUzeosd33nzE5MCNsZxCGEKTXaQ.png,Marvel Studios,US,299534
1,444,/42UPdZl6B2cFXgNUASR8hSt9mpS.png,Dune Entertainment,US,19995
2,574,/iB6GjNVHs5hOqcEYt2rcjBqIjki.png,Lightstorm Entertainment,US,19995
3,25,/qZCc1lty5FzX30aOCVRBLzaVmcp.png,20th Century Fox,US,19995
4,290,/Q8mw2AOQQc8Qg0uNwLWq86DVZv.png,Ingenious Media,GB,19995

3. __Load__ the datasets __into the database__ (each dataset should be a separate table in the database). __Name__ the tables "Movies", "Votes", "Genres", "Prod".

In [26]:
con = sq3.connect("movies.db")

In [27]:
con

In [28]:
movies.to_sql("Movies", con, index = False)

18

In [29]:
genres.to_sql("Genres", con,index = False )

55

In [30]:
prod.to_sql("Prod", con,index = False )

52

In [71]:
votes.to_sql("Votes", con,index = False )

18

In [31]:
con.execute("Select * FROM sqlite_master").fetchall()

[('table',
  'Movies',
  'Movies',
  2,
  'CREATE TABLE "Movies" (\n"id" INTEGER,\n  "title" TEXT,\n  "revenue" REAL,\n  "budget" REAL,\n  "belongs_to_collection_name" TEXT,\n  "release_date" TIMESTAMP\n)'),
 ('table',
  'Genres',
  'Genres',
  3,
  'CREATE TABLE "Genres" (\n"genre_id" INTEGER,\n  "genre_name" TEXT,\n  "id" INTEGER\n)'),
 ('table',
  'Prod',
  'Prod',
  4,
  'CREATE TABLE "Prod" (\n"comp_id" INTEGER,\n  "comp_logo_path" TEXT,\n  "comp_name" TEXT,\n  "comp_origin_country" TEXT,\n  "id" INTEGER\n)')]

In [32]:
con.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").fetchall()

[('Genres',), ('Movies',), ('Prod',)]

In [33]:
con.close()

## Loading Data from SQLite Databases into DataFrames

4. __Load__ the full tables "Movies", "Votes", "Genres", "Prod" from "movies.db" into Pandas (four DataFrames). __Set__ "id" as Index.

In [34]:
con = sq3.connect("movies.db")

In [35]:
con.execute("Select * FROM sqlite_master").fetchall()

[('table',
  'Movies',
  'Movies',
  2,
  'CREATE TABLE "Movies" (\n"id" INTEGER,\n  "title" TEXT,\n  "revenue" REAL,\n  "budget" REAL,\n  "belongs_to_collection_name" TEXT,\n  "release_date" TIMESTAMP\n)'),
 ('table',
  'Genres',
  'Genres',
  3,
  'CREATE TABLE "Genres" (\n"genre_id" INTEGER,\n  "genre_name" TEXT,\n  "id" INTEGER\n)'),
 ('table',
  'Prod',
  'Prod',
  4,
  'CREATE TABLE "Prod" (\n"comp_id" INTEGER,\n  "comp_logo_path" TEXT,\n  "comp_name" TEXT,\n  "comp_origin_country" TEXT,\n  "id" INTEGER\n)')]

In [36]:
pd.read_sql("SELECT * FROM Movies", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00
2,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00
3,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00
4,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00
5,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00
6,420818,The Lion King,1656.943394,260.0,None,2019-07-12 00:00:00
7,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00
8,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00
9,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00
10,284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13 00:00:00
11,12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07 00:00:00
12,181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13 00:00:00
13,330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20 00:00:00
14,351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06 00:00:00
15,109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27 00:00:00
16,321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16 00:00:00
17,260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14 00:00:00

In [37]:
df = pd.read_sql("SELECT * FROM Movies", con, index_col = "id", parse_dates = "release_date")
df

,title,revenue,budget,belongs_to_collection_name,release_date
id,,,,,
299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24
19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10
140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15
299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25
597,Titanic,1845.034188,200.0,None,1997-11-18
135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06
420818,The Lion King,1656.943394,260.0,None,2019-07-12
24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25
168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01
99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22
284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13
12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07
181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13
330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20
351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06
109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27
321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16
260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 299534 to 260513
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       18 non-null     object
 1   revenue                     18 non-null     float64
 2   budget                      18 non-null     float64
 3   belongs_to_collection_name  15 non-null     object
 4   release_date                18 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 864.0+ bytes

In [40]:
genres = pd.read_sql("SELECT * FROM Genres GROUP BY genre_name", con, index_col = "id")
genres

        genre_id       genre_name
id
299534        28           Action
299534        12        Adventure
330457        16        Animation
597           18            Drama
420818     10751           Family
19995         14          Fantasy
597        10749          Romance
299534       878  Science Fiction
135397        53         Thriller

In [41]:
con.close()

##  Some Simple SQL Queries

5. __Perform__ the following simple __SQL Queries__ and __store__ the results in DataFrames:

In [42]:
con = sq3.connect("movies.db")

__Load the full "Movies" Table__.

In [43]:
pd.read_sql("SELECT * FROM Movies", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00
2,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00
3,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00
4,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00
5,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00
6,420818,The Lion King,1656.943394,260.0,None,2019-07-12 00:00:00
7,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00
8,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00
9,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00
10,284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13 00:00:00
11,12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07 00:00:00
12,181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13 00:00:00
13,330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20 00:00:00
14,351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06 00:00:00
15,109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27 00:00:00
16,321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16 00:00:00
17,260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14 00:00:00

__Load the columns "id", "revenue" and "release_date" from "Movies".__

In [45]:
pd.read_sql("SELECT id, revenue, release_date FROM Movies", con)

        id      revenue         release_date
0   299534  2797.800564  2019-04-24 00:00:00
1    19995  2787.965087  2009-12-10 00:00:00
2   140607  2068.223624  2015-12-15 00:00:00
3   299536  2046.239637  2018-04-25 00:00:00
4      597  1845.034188  1997-11-18 00:00:00
5   135397  1671.713208  2015-06-06 00:00:00
6   420818  1656.943394  2019-07-12 00:00:00
7    24428  1519.557910  2012-04-25 00:00:00
8   168259  1515.047671  2015-04-01 00:00:00
9    99861  1405.403694  2015-04-22 00:00:00
10  284054  1346.739107  2018-02-13 00:00:00
11   12445  1341.511219  2011-07-07 00:00:00
12  181808  1332.539889  2017-12-13 00:00:00
13  330457  1330.764959  2019-11-20 00:00:00
14  351286  1303.459585  2018-06-06 00:00:00
15  109445  1274.219009  2013-11-27 00:00:00
16  321612  1263.521126  2017-03-16 00:00:00
17  260513  1241.891456  2018-06-14 00:00:00

__Get the Total Revenue (sum) over all movies from "Movies".__

In [46]:
pd.read_sql("SELECT sum(revenue) FROM Movies", con)

   sum(revenue)
0  29748.575327

__Count the number of Movies in "Movies".__

In [50]:
pd.read_sql("SELECT COUNT(*) FROM Movies", con)

   COUNT(*)
0        18

__Count the number of Movies that do belong to a collection.__

In [51]:
pd.read_sql("SELECT count(belongs_to_collection_name) FROM Movies", con)

   count(belongs_to_collection_name)
0                                 15

__Get the average budget from "Movies"__.

In [54]:
pd.read_sql("SELECT ROUND(AVG(budget),2) FROM Movies", con)

   ROUND(AVG(budget),2)
0                209.06

## Some more SQL Queries

6. __Perform__ the following advanced __SQL Queries__ and __store__ the results in DataFrames:

__Load all columns for the movie with movie id 597__.

In [57]:
pd.read_sql("SELECT * FROM Movies WHERE id = 597 ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00

__Load all columns for all movies with a revenue greater than 2000 (MUSD).__

In [58]:
pd.read_sql("SELECT * FROM Movies WHERE revenue>2000 ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00
2,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00
3,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00

__Load all columns for all movies with a revenue greater than 1500 (MUSD) and a budget below 200 (MUSD).__

In [59]:
pd.read_sql("SELECT * FROM Movies WHERE revenue>1500 AND budget<200 ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00
1,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00

__Get the minimum budget from those movies with a revenue greater than 1250 (MUSD).__

In [60]:
pd.read_sql("SELECT MIN(budget) FROM Movies WHERE revenue>1250 ", con)

   MIN(budget)
0        125.0

__Get all unique collection Names from "Movies".__

In [61]:
pd.read_sql("SELECT DISTINCT belongs_to_collection_name FROM Movies ", con)

            belongs_to_collection_name
0              The Avengers Collection
1                    Avatar Collection
2                 Star Wars Collection
3                                 None
4             Jurassic Park Collection
5  The Fast and the Furious Collection
6             Black Panther Collection
7              Harry Potter Collection
8                    Frozen Collection
9           The Incredibles Collection

__Load all movies (all columns) and sort by budget from high to low.__

In [62]:
pd.read_sql("SELECT * FROM Movies ORDER BY budget DESC ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00
2,420818,The Lion King,1656.943394,260.0,None,2019-07-12 00:00:00
3,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00
4,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00
5,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00
6,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00
7,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00
8,284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13 00:00:00
9,181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13 00:00:00
10,260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14 00:00:00
11,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00
12,351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06 00:00:00
13,321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16 00:00:00
14,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00
15,330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20 00:00:00
16,109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27 00:00:00
17,12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07 00:00:00

__Load all movies (all columns) that do not belong to a collection.__

In [63]:
pd.read_sql("SELECT * FROM Movies WHERE belongs_to_collection_name IS NULL  ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00
1,420818,The Lion King,1656.943394,260.0,None,2019-07-12 00:00:00
2,321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16 00:00:00

__Load all movies (all columns) that belong to a collection.__

In [64]:
pd.read_sql("SELECT * FROM Movies WHERE belongs_to_collection_name IS NOT NULL  ", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00
2,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00
3,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00
4,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00
5,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00
6,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00
7,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00
8,284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13 00:00:00
9,12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07 00:00:00
10,181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13 00:00:00
11,330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20 00:00:00
12,351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06 00:00:00
13,109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27 00:00:00
14,260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14 00:00:00

__Load all movies (all columns) where "Avengers..." is in the title__.

In [66]:
pd.read_sql("SELECT * FROM Movies WHERE title LIKE '%Avengers%'", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00
1,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00
2,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00
3,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00

## Join Queries

7. __Perform__ the following __SQL Join Queries__ and __store__ the results in DataFrames:

In [74]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", con)

     name
0  Movies
1  Genres
2    Prod
3   Votes

In [72]:
pd.read_sql("SELECT * FROM Votes", con)

        id  vote_count  vote_average
0   299534       12607           8.3
1    19995       21000           7.4
2   140607       14205           7.4
3   299536       17718           8.3
4      597       16661           7.8
5   135397       15399           6.6
6   420818        5425           7.2
7    24428       22101           7.7
8   168259        7359           7.3
9    99861       15548           7.3
10  284054       14830           7.4
11   12445       13447           8.1
12  181808       10304           7.0
13  330457        3982           7.2
14  351286        7337           6.5
15  109445       11616           7.3
16  321612       12203           6.9
17  260513        8147           7.5

__Join "Movies" and "Votes"__ (all columns).

In [73]:
pd.read_sql("SELECT * \
            FROM Movies \
            JOIN Votes \
            ON Movies.id=Votes.id", con)

,id,title,revenue,budget,belongs_to_collection_name,release_date,id,vote_count,vote_average
0,299534,Avengers: Endgame,2797.800564,356.0,The Avengers Collection,2019-04-24 00:00:00,299534,12607,8.3
1,19995,Avatar,2787.965087,237.0,Avatar Collection,2009-12-10 00:00:00,19995,21000,7.4
2,140607,Star Wars: The Force Awakens,2068.223624,245.0,Star Wars Collection,2015-12-15 00:00:00,140607,14205,7.4
3,299536,Avengers: Infinity War,2046.239637,300.0,The Avengers Collection,2018-04-25 00:00:00,299536,17718,8.3
4,597,Titanic,1845.034188,200.0,None,1997-11-18 00:00:00,597,16661,7.8
5,135397,Jurassic World,1671.713208,150.0,Jurassic Park Collection,2015-06-06 00:00:00,135397,15399,6.6
6,420818,The Lion King,1656.943394,260.0,None,2019-07-12 00:00:00,420818,5425,7.2
7,24428,The Avengers,1519.557910,220.0,The Avengers Collection,2012-04-25 00:00:00,24428,22101,7.7
8,168259,Furious 7,1515.047671,190.0,The Fast and the Furious Collection,2015-04-01 00:00:00,168259,7359,7.3
9,99861,Avengers: Age of Ultron,1405.403694,250.0,The Avengers Collection,2015-04-22 00:00:00,99861,15548,7.3
10,284054,Black Panther,1346.739107,200.0,Black Panther Collection,2018-02-13 00:00:00,284054,14830,7.4
11,12445,Harry Potter and the Deathly Hallows: Part 2,1341.511219,125.0,Harry Potter Collection,2011-07-07 00:00:00,12445,13447,8.1
12,181808,Star Wars: The Last Jedi,1332.539889,200.0,Star Wars Collection,2017-12-13 00:00:00,181808,10304,7.0
13,330457,Frozen II,1330.764959,150.0,Frozen Collection,2019-11-20 00:00:00,330457,3982,7.2
14,351286,Jurassic World: Fallen Kingdom,1303.459585,170.0,Jurassic Park Collection,2018-06-06 00:00:00,351286,7337,6.5
15,109445,Frozen,1274.219009,150.0,Frozen Collection,2013-11-27 00:00:00,109445,11616,7.3
16,321612,Beauty and the Beast,1263.521126,160.0,None,2017-03-16 00:00:00,321612,12203,6.9
17,260513,Incredibles 2,1241.891456,200.0,The Incredibles Collection,2018-06-14 00:00:00,260513,8147,7.5

__Join "Movies" and "Votes" (only the columns "id", "title", "vote_average").__

In [75]:
pd.read_sql("SELECT Movies.id, Movies.title, Votes.vote_average \
            FROM Movies \
            JOIN Votes \
            ON Movies.id=Votes.id", con, index_col = "id")

                                               title  vote_average
id
299534                             Avengers: Endgame           8.3
19995                                         Avatar           7.4
140607                  Star Wars: The Force Awakens           7.4
299536                        Avengers: Infinity War           8.3
597                                          Titanic           7.8
135397                                Jurassic World           6.6
420818                                 The Lion King           7.2
24428                                   The Avengers           7.7
168259                                     Furious 7           7.3
99861                        Avengers: Age of Ultron           7.3
284054                                 Black Panther           7.4
12445   Harry Potter and the Deathly Hallows: Part 2           8.1
181808                      Star Wars: The Last Jedi           7.0
330457                                     Frozen II           7.2
351286                Jurassic World: Fallen Kingdom           6.5
109445                                        Frozen           7.3
321612                          Beauty and the Beast           6.9
260513                                 Incredibles 2           7.5

__Join "Movies" and "Votes" (only the columns "id", "title", "vote_average") and return only those movies with vote_average > 8.__

In [76]:
pd.read_sql("SELECT Movies.id, Movies.title, Votes.vote_average \
            FROM Movies \
            JOIN Votes \
            ON Movies.id=Votes.id \
            WHERE vote_average>8", con, index_col = "id")

                                               title  vote_average
id
299534                             Avengers: Endgame           8.3
299536                        Avengers: Infinity War           8.3
12445   Harry Potter and the Deathly Hallows: Part 2           8.1

__Join "Movies" and "Votes" (only the columns "id", "title", "vote_average") and return only those movies with vote_average > 8 and in ascending budget order__.

In [77]:
pd.read_sql("SELECT Movies.id, Movies.title, Votes.vote_average \
            FROM Movies \
            JOIN Votes \
            ON Movies.id=Votes.id \
            WHERE vote_average>8 \
            ORDER BY budget", con, index_col = "id")

                                               title  vote_average
id
12445   Harry Potter and the Deathly Hallows: Part 2           8.1
299536                        Avengers: Infinity War           8.3
299534                             Avengers: Endgame           8.3

## Final Case Study

8. __Perform__ the following advanced __SQL Queries__ and __store__ the results in DataFrames:

__Get the Total Revenue (sum) for each Production Company.__

In [85]:
df = pd.read_sql("SELECT Prod.id, Prod.comp_name, Movies.revenue, Movies.title \
            FROM Prod \
            LEFT JOIN Movies \
            ON Prod.id=Movies.id", con)
df

,id,comp_name,revenue,title
0,299534,Marvel Studios,2797.800564,Avengers: Endgame
1,19995,Dune Entertainment,2787.965087,Avatar
2,19995,Lightstorm Entertainment,2787.965087,Avatar
3,19995,20th Century Fox,2787.965087,Avatar
4,19995,Ingenious Media,2787.965087,Avatar
5,140607,Truenorth Productions,2068.223624,Star Wars: The Force Awakens
6,140607,Lucasfilm,2068.223624,Star Wars: The Force Awakens
7,140607,Bad Robot,2068.223624,Star Wars: The Force Awakens
8,299536,Marvel Studios,2046.239637,Avengers: Infinity War
9,597,Paramount,1845.034188,Titanic
10,597,Lightstorm Entertainment,1845.034188,Titanic
11,597,20th Century Fox,1845.034188,Titanic
12,135397,Fuji Television Network,1671.713208,Jurassic World
13,135397,Amblin Entertainment,1671.713208,Jurassic World
14,135397,Legendary Entertainment,1671.713208,Jurassic World
15,135397,Universal Pictures,1671.713208,Jurassic World
16,135397,Dentsu,1671.713208,Jurassic World
17,135397,The Kennedy/Marshall Company,1671.713208,Jurassic World
18,420818,Walt Disney Pictures,1656.943394,The Lion King
19,420818,Fairview Entertainment,1656.943394,The Lion King
20,24428,Marvel Studios,1519.557910,The Avengers
21,24428,Paramount,1519.557910,The Avengers
22,168259,Abu Dhabi Film Commission,1515.047671,Furious 7
23,168259,Universal Pictures,1515.047671,Furious 7
24,168259,China Film Co.,1515.047671,Furious 7
25,168259,Original Film,1515.047671,Furious 7
26,168259,Fuji Television Network,1515.047671,Furious 7
27,168259,Québec Production Services Tax Credit,1515.047671,Furious 7
28,168259,"Colorado Office of Film, Television & Media",1515.047671,Furious 7
29,168259,Dentsu,1515.047671,Furious 7
30,168259,Media Rights Capital,1515.047671,Furious 7
31,168259,One Race,1515.047671,Furious 7
32,99861,Marvel Studios,1405.403694,Avengers: Age of Ultron
33,284054,Marvel Studios,1346.739107,Black Panther
34,284054,Walt Disney Pictures,1346.739107,Black Panther
35,12445,Warner Bros. Pictures,1341.511219,Harry Potter and the Deathly Hallows: Part 2
36,12445,Heyday Films,1341.511219,Harry Potter and the Deathly Hallows: Part 2
37,181808,Lucasfilm,1332.539889,Star Wars: The Last Jedi
38,181808,Ram Bergman Productions,1332.539889,Star Wars: The Last Jedi
39,181808,Walt Disney Pictures,1332.539889,Star Wars: The Last Jedi
40,330457,Walt Disney Animation Studios,1330.764959,Frozen II
41,330457,Walt Disney Pictures,1330.764959,Frozen II
42,351286,Amblin Entertainment,1303.459585,Jurassic World: Fallen Kingdom
43,351286,Legendary Entertainment,1303.459585,Jurassic World: Fallen Kingdom
44,351286,Universal Pictures,1303.459585,Jurassic World: Fallen Kingdom
45,351286,Perfect World Pictures,1303.459585,Jurassic World: Fallen Kingdom
46,109445,Walt Disney Pictures,1274.219009,Frozen
47,109445,Walt Disney Animation Studios,1274.219009,Frozen
48,321612,Walt Disney Pictures,1263.521126,Beauty and the Beast
49,321612,Mandeville Films,1263.521126,Beauty and the Beast
50,260513,Walt Disney Pictures,1241.891456,Incredibles 2
51,260513,Pixar,1241.891456,Incredibles 2

In [86]:
df.groupby("comp_name").revenue.sum().sort_values(ascending = False)

comp_name
Walt Disney Pictures                           9446.618940
Marvel Studios                                 9115.740912
20th Century Fox                               4632.999275
Lightstorm Entertainment                       4632.999275
Universal Pictures                             4490.220464
Lucasfilm                                      3400.763513
Paramount                                      3364.592098
Fuji Television Network                        3186.760879
Dentsu                                         3186.760879
Legendary Entertainment                        2975.172793
Amblin Entertainment                           2975.172793
Ingenious Media                                2787.965087
Dune Entertainment                             2787.965087
Walt Disney Animation Studios                  2604.983968
Bad Robot                                      2068.223624
Truenorth Productions                          2068.223624
The Kennedy/Marshall Company                   1671.713208
Fairview Entertainment                         1656.943394
Colorado Office of Film, Television & Media    1515.047671
Abu Dhabi Film Commission                      1515.047671
China Film Co.                                 1515.047671
Media Rights Capital                           1515.047671
One Race                                       1515.047671
Original Film                                  1515.047671
Québec Production Services Tax Credit          1515.047671
Warner Bros. Pictures                          1341.511219
Heyday Films                                   1341.511219
Ram Bergman Productions                        1332.539889
Perfect World Pictures                         1303.459585
Mandeville Films                               1263.521126
Pixar                                          1241.891456
Name: revenue, dtype: float64

__Get all Production Companies for the movie "Titanic".__

In [87]:
pd.read_sql("SELECT  Prod.comp_name \
            FROM Prod \
            LEFT JOIN Movies \
            ON Prod.id=Movies.id \
            WHERE Movies.title = 'Titanic'", con)

                  comp_name
0          20th Century Fox
1  Lightstorm Entertainment
2                 Paramount

__Get the Total Revenue (sum) for each Genre.__

In [88]:
df2 = pd.read_sql("SELECT Genres.id, Genres.genre_name, Movies.revenue, Movies.title \
            FROM Genres \
            LEFT JOIN Movies \
            ON Genres.id=Movies.id", con)
df2

,id,genre_name,revenue,title
0,299534,Adventure,2797.800564,Avengers: Endgame
1,299534,Science Fiction,2797.800564,Avengers: Endgame
2,299534,Action,2797.800564,Avengers: Endgame
3,19995,Action,2787.965087,Avatar
4,19995,Adventure,2787.965087,Avatar
5,19995,Fantasy,2787.965087,Avatar
6,19995,Science Fiction,2787.965087,Avatar
7,140607,Action,2068.223624,Star Wars: The Force Awakens
8,140607,Adventure,2068.223624,Star Wars: The Force Awakens
9,140607,Science Fiction,2068.223624,Star Wars: The Force Awakens
10,140607,Fantasy,2068.223624,Star Wars: The Force Awakens
11,299536,Adventure,2046.239637,Avengers: Infinity War
12,299536,Action,2046.239637,Avengers: Infinity War
13,299536,Science Fiction,2046.239637,Avengers: Infinity War
14,597,Drama,1845.034188,Titanic
15,597,Romance,1845.034188,Titanic
16,135397,Action,1671.713208,Jurassic World
17,135397,Adventure,1671.713208,Jurassic World
18,135397,Science Fiction,1671.713208,Jurassic World
19,135397,Thriller,1671.713208,Jurassic World
20,420818,Adventure,1656.943394,The Lion King
21,420818,Family,1656.943394,The Lion King
22,24428,Science Fiction,1519.557910,The Avengers
23,24428,Action,1519.557910,The Avengers
24,24428,Adventure,1519.557910,The Avengers
25,168259,Action,1515.047671,Furious 7
26,168259,Thriller,1515.047671,Furious 7
27,99861,Action,1405.403694,Avengers: Age of Ultron
28,99861,Adventure,1405.403694,Avengers: Age of Ultron
29,99861,Science Fiction,1405.403694,Avengers: Age of Ultron
30,284054,Action,1346.739107,Black Panther
31,284054,Adventure,1346.739107,Black Panther
32,284054,Fantasy,1346.739107,Black Panther
33,284054,Science Fiction,1346.739107,Black Panther
34,12445,Fantasy,1341.511219,Harry Potter and the Deathly Hallows: Part 2
35,12445,Adventure,1341.511219,Harry Potter and the Deathly Hallows: Part 2
36,181808,Science Fiction,1332.539889,Star Wars: The Last Jedi
37,181808,Action,1332.539889,Star Wars: The Last Jedi
38,181808,Adventure,1332.539889,Star Wars: The Last Jedi
39,330457,Animation,1330.764959,Frozen II
40,330457,Family,1330.764959,Frozen II
41,330457,Adventure,1330.764959,Frozen II
42,351286,Action,1303.459585,Jurassic World: Fallen Kingdom
43,351286,Adventure,1303.459585,Jurassic World: Fallen Kingdom
44,351286,Science Fiction,1303.459585,Jurassic World: Fallen Kingdom
45,109445,Animation,1274.219009,Frozen
46,109445,Adventure,1274.219009,Frozen
47,109445,Family,1274.219009,Frozen
48,321612,Family,1263.521126,Beauty and the Beast
49,321612,Fantasy,1263.521126,Beauty and the Beast
50,321612,Romance,1263.521126,Beauty and the Beast
51,260513,Action,1241.891456,Incredibles 2
52,260513,Adventure,1241.891456,Incredibles 2
53,260513,Animation,1241.891456,Incredibles 2
54,260513,Family,1241.891456,Incredibles 2

In [89]:
df2.groupby("genre_name").revenue.sum().sort_values(ascending = False)

genre_name
Adventure          25124.972342
Action             21036.581432
Science Fiction    18279.642305
Fantasy             8807.960163
Family              6767.339944
Animation           3846.875424
Thriller            3186.760879
Romance             3108.555314
Drama               1845.034188
Name: revenue, dtype: float64

__Get all Genres for the movie "Frozen II".__

In [90]:
pd.read_sql("SELECT Genres.genre_name \
            FROM Genres \
            LEFT JOIN Movies \
            ON Genres.id=Movies.id \
            WHERE Movies.title = 'Frozen II'", con)

  genre_name
0  Adventure
1  Animation
2     Family

In [91]:
con.close()