# Project 6: Importing & Merging many files (Baby Names Dataset) - Part 1

In [1]:
import pandas as pd

## Importing one File & Understanding the Data Structure

2. __Load__ the file __"yob1880.txt"__ into Pandas and __inspect__.

In [4]:
pd.read_csv("yob1880.txt")

           Mary  F  7065
0          Anna  F  2604
1          Emma  F  2003
2     Elizabeth  F  1939
3        Minnie  F  1746
4      Margaret  F  1578
...         ... ..   ...
1994     Woodie  M     5
1995     Worthy  M     5
1996     Wright  M     5
1997       York  M     5
1998  Zachariah  M     5

[1999 rows x 3 columns]

In [5]:
df = pd.read_csv("yob1880.txt", header = None, names = ["Name", "Gender", "Count"])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2000 non-null   object
 1   Gender  2000 non-null   object
 2   Count   2000 non-null   int64
dtypes: int64(1), object(2)
memory usage: 47.0+ KB

## Importing & merging many files (easy case)

3. __Load__ all files (yob????.txt) and __merge/concatenate__ all files into one Pandas DataFrame. Make sure you add the __column "Year"__.

In [7]:
df_1880 = pd.read_csv("yob1880.txt", header = None, names = ["Name", "Gender", "Count"])
df_1880

           Name Gender  Count
0          Mary      F   7065
1          Anna      F   2604
2          Emma      F   2003
3     Elizabeth      F   1939
4        Minnie      F   1746
...         ...    ...    ...
1995     Woodie      M      5
1996     Worthy      M      5
1997     Wright      M      5
1998       York      M      5
1999  Zachariah      M      5

[2000 rows x 3 columns]

In [9]:
years = list(range(1880, 2019))

In [10]:
dataframes = []
for year in years:
    data = pd.read_csv("yob{}.txt".format(year), header = None, 
                       names = ["Name", "Gender", "Count"])
    dataframes.append(data)

In [11]:
len(dataframes)

139

In [12]:
df = pd.concat(dataframes,  axis = 0, keys = years, names = ["Year"]).droplevel(-1).reset_index()

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1957046 entries, 0 to 1957045
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   Year    int64
 1   Name    object
 2   Gender  object
 3   Count   int64
dtypes: int64(2), object(2)
memory usage: 59.7+ MB

In [14]:
df.head()

   Year       Name Gender  Count
0  1880       Mary      F   7065
1  1880       Anna      F   2604
2  1880       Emma      F   2003
3  1880  Elizabeth      F   1939
4  1880     Minnie      F   1746

In [15]:
df.tail()

         Year   Name Gender  Count
1957041  2018  Zylas      M      5
1957042  2018  Zyran      M      5
1957043  2018  Zyrie      M      5
1957044  2018  Zyron      M      5
1957045  2018  Zzyzx      M      5

4. Create a __RangeIndex__ and __save__ the DataFrame (with columns "Year", "Name", "Gender" and "Count") in a new csv-file.

In [16]:
df.to_csv("us_baby_names.csv", index = False)

In [17]:
pd.read_csv("us_baby_names.csv")

         Year       Name Gender  Count
0        1880       Mary      F   7065
1        1880       Anna      F   2604
2        1880       Emma      F   2003
3        1880  Elizabeth      F   1939
4        1880     Minnie      F   1746
...       ...        ...    ...    ...
1957041  2018      Zylas      M      5
1957042  2018      Zyran      M      5
1957043  2018      Zyrie      M      5
1957044  2018      Zyron      M      5
1957045  2018      Zzyzx      M      5

[1957046 rows x 4 columns]