# Project 6: Importing & Merging many files (Baby Names Dataset) - Part 2

## Importing one File & Understanding the Data Structure

2. __Load__ the file __"AK.txt"__ into Pandas and __inspect__.

In [1]:
import pandas as pd

In [4]:
pd.read_csv('/Users/anoushka/Desktop/Project_06_Materials/namesbystate/AK.TXT')

       AK  F  1910      Mary  14
0      AK  F  1910     Annie  12
1      AK  F  1910      Anna  10
2      AK  F  1910  Margaret   8
3      AK  F  1910     Helen   7
4      AK  F  1910     Elsie   6
...    .. ..   ...       ...  ..
28522  AK  M  2018      Theo   5
28523  AK  M  2018    Thorin   5
28524  AK  M  2018   Trenton   5
28525  AK  M  2018    Victor   5
28526  AK  M  2018      Zion   5

[28527 rows x 5 columns]

In [5]:
pd.read_csv("AK.TXT", header = None, names = ["State", "Gender", "Year", "Name", "Count"])

      State Gender  Year      Name  Count
0        AK      F  1910      Mary     14
1        AK      F  1910     Annie     12
2        AK      F  1910      Anna     10
3        AK      F  1910  Margaret      8
4        AK      F  1910     Helen      7
...     ...    ...   ...       ...    ...
28523    AK      M  2018      Theo      5
28524    AK      M  2018    Thorin      5
28525    AK      M  2018   Trenton      5
28526    AK      M  2018    Victor      5
28527    AK      M  2018      Zion      5

[28528 rows x 5 columns]

## The glob module

3. From glob import glob.

In [6]:
from glob import glob

4. __Find__ all filenames with the structure __"A?.txt"__ in your current directory (? is a single charcter wildcard).

In [7]:
glob("A?.TXT")

['AR.TXT', 'AZ.TXT', 'AL.TXT', 'AK.TXT']

5. __Find__ all filenames with the following structure in your current directory and save the resulting list in a variable:

In [10]:
a = (glob("*.TXT"))

In [15]:
len(a)

51

# Importing & merging many Files (complex case)

6. __Load__ all files (*.txt) and __merge/concatenate__ all files into one Pandas DataFrame.

In [13]:
dataframes = []
for file in a:
    data = pd.read_csv(file, header = None, 
                       names = ["State","Gender","Year"	,"Name","Count"])
    dataframes.append(data)

In [14]:
len(dataframes)

51

In [16]:
df = pd.concat(dataframes, ignore_index = True)

In [17]:
df.head()

  State Gender  Year     Name  Count
0    IN      F  1910     Mary    619
1    IN      F  1910    Helen    324
2    IN      F  1910     Ruth    238
3    IN      F  1910  Dorothy    215
4    IN      F  1910  Mildred    200

7. Create a __RangeIndex__ and __save__ the DataFrame (with columns "State", "Gender", "Year", "Name", "Count") in a new csv-file.

In [18]:
df.to_csv("baby_names_state.csv", index = False)

In [19]:
pd.read_csv("baby_names_state.csv")

        State Gender  Year     Name  Count
0          IN      F  1910     Mary    619
1          IN      F  1910    Helen    324
2          IN      F  1910     Ruth    238
3          IN      F  1910  Dorothy    215
4          IN      F  1910  Mildred    200
...       ...    ...   ...      ...    ...
6028146    DE      M  2018    Rocco      5
6028147    DE      M  2018    Rylan      5
6028148    DE      M  2018    Semaj      5
6028149    DE      M  2018   Steven      5
6028150    DE      M  2018   Thiago      5

[6028151 rows x 5 columns]