# Project 3: Data Cleaning - Tidy up messy Datasets (Movies Dataset)

In [2]:
import pandas as pd

## First Steps

1. __Load__ and __inspect__ the messy dataset __movies_metadata.csv__. Identify columns with nested / stringified json data.

In [ ]:
df = pd.read_csv('/Users/anoushka/Desktop/Data Science Portfolio/movies_metadata.csv',low_memory=False)

In [9]:
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [10]:
df.head()

,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4494 non-null   object
 1   budget                 45466 non-null  object
 2   genres                 45466 non-null  object
 3   homepage               7782 non-null   object
 4   id                     45466 non-null  object
 5   imdb_id                45449 non-null  object
 6   original_language      45455 non-null  object
 7   original_title         45466 non-null  object
 8   overview               44512 non-null  object
 9   popularity             45461 non-null  object
 10  poster_path            45080 non-null  object
 11  production_companies   45463 non-null  object
 12  production_countries   45463 non-null  object
 13  release_date           45379 non-null  object
 14  revenue                45460 non-null  float64
 15  runtime                45203 non-null  float64
 16  spoken_languages       45460 non-null  object
 17  status                 45379 non-null  object
 18  tagline                20412 non-null  object
 19  title                  45460 non-null  object
 20  video                  45460 non-null  object
 21  vote_average           45460 non-null  float64
 22  vote_count             45460 non-null  float64
dtypes: float64(4), object(19)
memory usage: 8.0+ MB

In [13]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

## Dropping irrelevant Columns

2. __Drop__ the irrelevant columns 'adult', 'imdb_id', 'original_title', 'video' and 'homepage'.

In [7]:
df.drop('adult',axis=1,inplace = True)

In [14]:
df.drop('imdb_id',axis = 1,inplace = True)

In [15]:
df.drop('original_title',axis = 1,inplace = True)

In [16]:
df.drop('video',axis = 1,inplace = True)

In [17]:
df.drop('homepage',axis = 1,inplace = True)

In [18]:
df['genres']

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                           [{'id': 35, 'name': 'Comedy'}]
                               ...
45461    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                        [{'id': 18, 'name': 'Drama'}]
45463    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                   []
45465                                                   []
Name: genres, Length: 45466, dtype: object

In [19]:
df['belongs_to_collection']

0        {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                      NaN
2        {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                      NaN
4        {'id': 96871, 'name': 'Father of the Bride Col...
                               ...
45461                                                  NaN
45462                                                  NaN
45463                                                  NaN
45464                                                  NaN
45465                                                  NaN
Name: belongs_to_collection, Length: 45466, dtype: object

In [20]:
df['production_companies']

0           [{'name': 'Pixar Animation Studios', 'id': 3}]
1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3        [{'name': 'Twentieth Century Fox Film Corporat...
4        [{'name': 'Sandollar Productions', 'id': 5842}...
                               ...
45461                                                   []
45462               [{'name': 'Sine Olivia', 'id': 19653}]
45463    [{'name': 'American World Pictures', 'id': 6165}]
45464                 [{'name': 'Yermoliev', 'id': 88753}]
45465                                                   []
Name: production_companies, Length: 45466, dtype: object

In [21]:
df['production_countries']

0        [{'iso_3166_1': 'US', 'name': 'United States o...
1        [{'iso_3166_1': 'US', 'name': 'United States o...
2        [{'iso_3166_1': 'US', 'name': 'United States o...
3        [{'iso_3166_1': 'US', 'name': 'United States o...
4        [{'iso_3166_1': 'US', 'name': 'United States o...
                               ...
45461               [{'iso_3166_1': 'IR', 'name': 'Iran'}]
45462        [{'iso_3166_1': 'PH', 'name': 'Philippines'}]
45463    [{'iso_3166_1': 'US', 'name': 'United States o...
45464             [{'iso_3166_1': 'RU', 'name': 'Russia'}]
45465     [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]
Name: production_countries, Length: 45466, dtype: object

In [22]:
df['spoken_languages']

0                 [{'iso_639_1': 'en', 'name': 'English'}]
1        [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2                 [{'iso_639_1': 'en', 'name': 'English'}]
3                 [{'iso_639_1': 'en', 'name': 'English'}]
4                 [{'iso_639_1': 'en', 'name': 'English'}]
                               ...
45461               [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462                    [{'iso_639_1': 'tl', 'name': ''}]
45463             [{'iso_639_1': 'en', 'name': 'English'}]
45464                                                   []
45465             [{'iso_639_1': 'en', 'name': 'English'}]
Name: spoken_languages, Length: 45466, dtype: object

We can see the columns contain stringified JSON columns. We need to handle them, by converting back to python objects using 'ast.literal_eval()' method

## How to handle stringified JSON columns

3. __Evaluate__ Python Expressions in the stringified columns ["belongs_to_collection", "genres", "production_countries", "production_companies", "spoken_languages"] and __remove quotes__ ("") where possible.

In [23]:
import ast

In [24]:
cols = ["belongs_to_collection", "genres", "production_countries", "production_companies", "spoken_languages"]

In [26]:
for col in cols:
    df[col] = df[col].apply(
        lambda x: ast.literal_eval(x) if pd.notna(x) else x
    )

In [27]:
type(df['genres'].iloc[0])

list

In [28]:
type(df['belongs_to_collection'].iloc[0])

dict

## How to flatten nested Columns

4. __Extract__ only the __collection name__ from the column "belongs_to_collection" and __overwrite__ "belongs_to_collection". <br> For example: The value in the first row (Toy Story) should be 'Toy Story Collection'.

In [30]:
df['belongs_to_collection'][0]

{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}

In [31]:
df['belongs_to_collection'] = df['belongs_to_collection'].apply(
    lambda x: x['name'] if isinstance(x,dict) else None
)

In [32]:
df['belongs_to_collection']

0                  Toy Story Collection
1                                  None
2             Grumpy Old Men Collection
3                                  None
4        Father of the Bride Collection
                      ...
45461                              None
45462                              None
45463                              None
45464                              None
45465                              None
Name: belongs_to_collection, Length: 45466, dtype: object

In [37]:
df['belongs_to_collection'].value_counts()

belongs_to_collection
The Bowery Boys                  29
Totò Collection                  27
James Bond Collection            26
Zatôichi: The Blind Swordsman    26
The Carry On Collection          25
                                 ..
Glass Tiger collection            1
Kathleen Madigan Collection       1
The Big Bottom Box                1
Joséphine - Saga                  1
Red Lotus Collection              1
Name: count, Length: 1695, dtype: int64

5. __Extract__ all __genre names__ from the column "genres" and __overwrite__ "genres". If a movie has more than one genre, __seperate genres by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Animation|Comedy|Family'.

In [38]:
df['genres']

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                           [{'id': 35, 'name': 'Comedy'}]
                               ...
45461    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                        [{'id': 18, 'name': 'Drama'}]
45463    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                   []
45465                                                   []
Name: genres, Length: 45466, dtype: object

In [39]:
df['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [40]:
df.genres = df.genres.apply(lambda x: "|".join(i['name'] for i in x))

In [41]:
df['genres'][0]

'Animation|Comedy|Family'

In [46]:
df['genres'].value_counts()

genres
Drama                              5000
Comedy                             3621
Documentary                        2723
                                   2442
Drama|Romance                      1301
                                   ...
Action|Drama|Comedy|Documentary       1
War|Drama|History|Thriller            1
Horror|Drama|History|Thriller         1
Comedy|Crime|Action|Drama             1
Family|Animation|Romance|Comedy       1
Name: count, Length: 4069, dtype: int64

6. __Extract__ all __spoken language names__ from the column "spoken_languages" and __overwrite__ "spoken_languages". If a movie has more than one spoken language, __seperate spoken languages by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'English'.

In [48]:
df['spoken_languages'].head()

0             [{'iso_639_1': 'en', 'name': 'English'}]
1    [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2             [{'iso_639_1': 'en', 'name': 'English'}]
3             [{'iso_639_1': 'en', 'name': 'English'}]
4             [{'iso_639_1': 'en', 'name': 'English'}]
Name: spoken_languages, dtype: object

In [53]:
df.spoken_languages = df.spoken_languages.apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x,list)else None)

In [55]:
df['spoken_languages'][0]

'English'

In [56]:
df['spoken_languages'].head()

0             English
1    English|Français
2             English
3             English
4             English
Name: spoken_languages, dtype: object

In [57]:
df['spoken_languages'].value_counts()

spoken_languages
English                           22395
                                   3952
Français                           1853
日本語                                1289
Italiano                           1218
                                  ...
Deutsch||ελληνικά|English             1
English|suomi|Deutsch|svenska         1
English|Français|Deutsch|فارسی        1
svenska|English|Español               1
Fulfulde|English                      1
Name: count, Length: 1842, dtype: int64

7.__Extract__ all __production companies names__ from the column "production_companies" and __overwrite__ "production_companies". If a movie has more than one production company, __seperate production companies by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'Pixar Animation Studios'

In [58]:
df['production_companies'][0]

[{'name': 'Pixar Animation Studios', 'id': 3}]

In [59]:
df['production_companies'] = df['production_companies'].apply(lambda x: "|".join(i["name"] for i in x)if isinstance(x,list)else None)

In [60]:
df['production_companies'][0]

'Pixar Animation Studios'

In [61]:
df['production_companies'].head()

0                              Pixar Animation Studios
1    TriStar Pictures|Teitler Film|Interscope Commu...
2                          Warner Bros.|Lancaster Gate
3               Twentieth Century Fox Film Corporation
4            Sandollar Productions|Touchstone Pictures
Name: production_companies, dtype: object

In [62]:
df['production_companies'].value_counts()

production_companies
                                                                                                                                              11875
Metro-Goldwyn-Mayer (MGM)                                                                                                                       742
Warner Bros.                                                                                                                                    540
Paramount Pictures                                                                                                                              505
Twentieth Century Fox Film Corporation                                                                                                          439
                                                                                                                                              ...
HBO Films|Moving Pictures                                                                                                                         1
BIM Distribuzione|Canal+|Alta Producción|Centre National de la Cinématographie (CNC)|Rézo Productions|Compagnie Eric Rohmer (CER)|Cinémage        1
Galatée Films|Novo Arturo Films|Constantin Film Produktion|Pathé|France 2 Cinéma|France 3 Cinema|Logline Studios|Blue Screen Productions          1
Fox Searchlight Pictures|26 Films                                                                                                                 1
Yermoliev                                                                                                                                         1
Name: count, Length: 22672, dtype: int64

8.  __Extract__ all __production countries names__ from the column "production_countries" and __overwrite__ "production_countries". If a movie has more than one production country, __seperate production countries by a pipe__ "|".<br>
For example: The value in the first row (Toy Story) should be 'United States of America'.

In [65]:
df['production_countries'].head()

0    [{'iso_3166_1': 'US', 'name': 'United States o...
1    [{'iso_3166_1': 'US', 'name': 'United States o...
2    [{'iso_3166_1': 'US', 'name': 'United States o...
3    [{'iso_3166_1': 'US', 'name': 'United States o...
4    [{'iso_3166_1': 'US', 'name': 'United States o...
Name: production_countries, dtype: object

In [66]:
df['production_countries'] = df['production_countries'].apply(lambda x: "|".join(i["name"] for i in x)if isinstance(x,list)else None)

In [67]:
df['production_countries'][0]

'United States of America'

In [69]:
df['production_countries'].head(20)

0                          United States of America
1                          United States of America
2                          United States of America
3                          United States of America
4                          United States of America
5                          United States of America
6                  Germany|United States of America
7                          United States of America
8                          United States of America
9           United Kingdom|United States of America
10                         United States of America
11                  France|United States of America
12                         United States of America
13                         United States of America
14    France|Germany|Italy|United States of America
15                  France|United States of America
16          United Kingdom|United States of America
17                         United States of America
18                         United States of America
19                         United States of America
Name: production_countries, dtype: object

In [72]:
df['production_countries'].value_counts()

production_countries
United States of America                  17851
                                           6282
United Kingdom                             2238
France                                     1654
Japan                                      1356
                                          ...
Romania|United Kingdom|Canada                 1
Finland|Germany|Netherlands                   1
France|Denmark|Spain|Sweden                   1
France|United States of America|Canada        1
Egypt|Italy|United States of America          1
Name: count, Length: 2390, dtype: int64

9. __Inspect__ all columns above with value_counts(). Do you see anything strange? __Take reasonable measures__!

In [73]:
(df['production_countries'] == '').sum()

np.int64(6282)

In [74]:
import numpy as np

cols = [
    'genres',
    'spoken_languages',
    'production_companies',
    'production_countries'
]

for col in cols:
    df[col] = df[col].replace('', np.nan)

In [76]:
for col in cols:
    print((df[col] == '').sum())

0
0
0
0

In [78]:
df.isna().sum()

belongs_to_collection    40975
budget                       0
genres                    2442
id                           0
original_language           11
overview                   954
popularity                   5
poster_path                386
production_companies     11881
production_countries      6288
release_date                87
revenue                      6
runtime                    263
spoken_languages          3958
status                      87
tagline                  25054
title                        6
vote_average                 6
vote_count                   6
dtype: int64

In [79]:
(df['budget'] == 0).sum()
(df['revenue'] == 0).sum()
(df['runtime'] == 0).sum()

np.int64(1558)

In [80]:
df[['budget','id','popularity']].info()
df[['budget','revenue','runtime']].describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   budget      45466 non-null  object
 1   id          45466 non-null  object
 2   popularity  45461 non-null  object
dtypes: object(3)
memory usage: 1.0+ MB

            revenue       runtime
count  4.546000e+04  45203.000000
mean   1.120935e+07     94.128199
std    6.433225e+07     38.407810
min    0.000000e+00      0.000000
25%    0.000000e+00     85.000000
50%    0.000000e+00     95.000000
75%    0.000000e+00    107.000000
max    2.787965e+09   1256.000000

As we can see, these columns are object, and should be converted to numeric type.

## Cleaning Numerical Columns

10. __Convert__ the datatype in the columns __"budget"__, __"id"__ and __"popularity"__ __to numeric__. Set invalid values as NaN.

In [81]:
df['budget'] = pd.to_numeric(df['budget'],errors = 'coerce')

In [82]:
df.budget

0        30000000.0
1        65000000.0
2               0.0
3        16000000.0
4               0.0
            ...
45461           0.0
45462           0.0
45463           0.0
45464           0.0
45465           0.0
Name: budget, Length: 45466, dtype: float64

In [83]:
df['budget'] = df['budget'].replace(0,np.nan)

In [84]:
df.budget

0        30000000.0
1        65000000.0
2               NaN
3        16000000.0
4               NaN
            ...
45461           NaN
45462           NaN
45463           NaN
45464           NaN
45465           NaN
Name: budget, Length: 45466, dtype: float64

In [86]:
df['budget'].value_counts()

budget
5000000.0     286
10000000.0    259
20000000.0    243
2000000.0     242
15000000.0    226
             ...
9750000.0       1
7275000.0       1
78146652.0      1
280.0           1
1254040.0       1
Name: count, Length: 1222, dtype: int64

In [87]:
df['id'] = pd.to_numeric(df['id'],errors = 'coerce')

In [88]:
df['id'] = df['id'].replace(0,np.nan)

In [90]:
df['id'].value_counts()

id
141971.0    3
5511.0      2
132641.0    2
10991.0     2
168538.0    2
           ..
55135.0     1
15877.0     1
72272.0     1
1549.0      1
461257.0    1
Name: count, Length: 45433, dtype: int64

In [91]:
df['popularity'] = pd.to_numeric(df['popularity'],errors = 'coerce')

In [92]:
df['popularity'] = df['popularity'].replace(0,np.nan)

In [93]:
df['popularity'].value_counts()

popularity
0.000001    56
0.000308    43
0.000220    40
0.001177    38
0.000844    38
            ..
4.762242     1
6.173752     1
0.645652     1
0.556292     1
0.163015     1
Name: count, Length: 43756, dtype: int64

11. __Analyze__ the columns __"budget"__ and __"revenue"__ and __"runtime"__. Analyze movies with a budget/revenue/runtime of 0. Do you think the value 0 is the most appropriate value? __Take reasonable measures__!

In [94]:
cols = ['budget','revenue','runtime']

In [107]:
for col in cols:
    df[col]=df[col].replace(0,np.nan)

In [109]:
(df['budget'] == 0).sum()

np.int64(0)

In [110]:
df['budget'].isna().sum()

np.int64(36576)

In [111]:
(df['runtime'] == 0).sum()

np.int64(0)

In [112]:
(df['revenue']==0).sum()

np.int64(0)

In [113]:
df['runtime'].isna().sum()

np.int64(1821)

In [114]:
df['revenue'].isna().sum()

np.int64(38058)

The value 0 is not an appropriate value for many entries in the budget, revenue, and runtime columns. A movie cannot realistically have a runtime of 0 minutes, and a large number of budget/revenue values equal to 0 likely indicate missing or unavailable information rather than true zero values. Therefore, the zeros were replaced with missing values (NaN) to better represent the underlying data and avoid misleading statistical analyses.

12. The columns "budget" and "revenue" shall show values in Million USD. __Convert and Overwrite__!

In [115]:
cols = ['budget', 'revenue']

for col in cols:
    df[col] = df[col] / 1_000_000

In [116]:
df[['budget', 'revenue']].head()

   budget     revenue
0    30.0  373.554033
1    65.0  262.797249
2     NaN         NaN
3    16.0   81.452156
4     NaN   76.578911

13. __Analyze__ movies with a __vote_count of 0__. What´s the __vote_average__ for those movies? Do you think this value is the most appropriate value? __Take reasonable measures__!

In [119]:
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
df[df['vote_count']==0][['title','revenue','vote_average']]

                              title  revenue  vote_average
83      Last Summer in the Hamptons      NaN           0.0
107    Headless Body in Topless Bar      NaN           0.0
126                  Jupiter's Wife      NaN           0.0
132                   Sonic Outlaws      NaN           0.0
137                          Target      NaN           0.0
...                             ...      ...           ...
45432                 Altar of Fire      NaN           0.0
45434        The Wonders of Aladdin      NaN           0.0
45452                   Deep Hearts      NaN           0.0
45464              Satan Triumphant      NaN           0.0
45465                      Queerama      NaN           0.0

[2899 rows x 3 columns]

In [121]:
(df['vote_count'] == 0).sum()

np.int64(2899)

In [122]:
((df['vote_count'] == 0) & (df['vote_average'] == 0)).sum()

np.int64(2899)

In [123]:
df.loc[df['vote_count'] == 0, 'vote_average'] = np.nan

In [124]:
df['vote_average'].isna().sum()

np.int64(2905)

Movies with vote_count = 0 all had vote_average = 0. Since an average rating cannot be meaningfully computed without any votes, the value 0 appears to represent missing information rather than an actual rating. Therefore, these values were replaced with NaN.

## Cleaning DateTime Columns

14. __Convert__ the datatype in the column __"release_date"__ __to datetime__. Set invalid values as NaN.

In [125]:
df['release_date']

0        1995-10-30
1        1995-12-15
2        1995-12-22
3        1995-12-22
4        1995-02-10
            ...
45461           NaN
45462    2011-11-17
45463    2003-08-01
45464    1917-10-21
45465    2017-06-09
Name: release_date, Length: 45466, dtype: object

In [129]:
df['release_date'].dtype

dtype('O')

In [130]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

In [131]:
df['release_date']

0       1995-10-30
1       1995-12-15
2       1995-12-22
3       1995-12-22
4       1995-02-10
           ...
45461          NaT
45462   2011-11-17
45463   2003-08-01
45464   1917-10-21
45465   2017-06-09
Name: release_date, Length: 45466, dtype: datetime64[ns]

In [132]:
df['release_date'].dtype

dtype('<M8[ns]')

## Cleaning Text / String Columns

15. __Analyze__ the text columns "overview" and "tagline". Try to identify __missing data that is not represented by NaN__ (e.g. "No Data"). __Replace as NaN__ (np.nan)!

In [133]:
df['overview']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
45461          Rising and falling between a man and woman.
45462    An artist struggles to finish his work while a...
45463    When one of her hits goes wrong, a professiona...
45464    In a small town live two brothers, one a minis...
45465    50 years after decriminalisation of homosexual...
Name: overview, Length: 45466, dtype: object

In [134]:
(df['overview'] == '').sum()
(df['tagline'] == '').sum()

np.int64(0)

In [135]:
import numpy as np

cols = ['overview', 'tagline']

for col in cols:
    df[col] = df[col].replace(
        ['No Data', 'N/A', 'None', '', 'nan', 'NaN'],
        np.nan
    )

In [136]:
df['overview'].isna().sum()

np.int64(954)

In [137]:
df['tagline'].isna().sum()

np.int64(25054)

## Removing Duplicates

16. __Identify__ and __remove__ duplicates!

In [140]:
df.duplicated().sum()

np.int64(17)

In [141]:
df[df.duplicated()]

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1465,None,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinéma...,Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
9165,None,NaN,Crime|Drama|Thriller,5511.0,fr,Hitman Jef Costello is a perfectionist who alw...,9.091288,/cvNW8IXigbaMNo4gKEIps0NGnhA.jpg,Fida cinematografica|Compagnie Industrielle et...,France|Italy,1967-10-25,0.039481,105.0,Français,Released,There is no solitude greater than that of the ...,Le Samouraï,7.9,187.0
9327,None,NaN,Adventure|Animation|Drama|Action|Foreign,23305.0,en,"In feudal India, a warrior (Khan) who renounce...",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,Filmfour,France|Germany|India|United Kingdom,2001-09-23,NaN,86.0,हिन्दी,Released,NaN,The Warrior,6.3,15.0
13375,None,NaN,Thriller|Mystery,141971.0,fi,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or t...,Blackout,6.7,3.0
16764,None,NaN,Thriller|Mystery,141971.0,fi,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or t...,Blackout,6.7,3.0
21165,None,NaN,Fantasy|Drama|Science Fiction,119916.0,en,"Prospero, the true Duke of Milan is now living...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,NaN,NaN,1980-02-27,NaN,123.0,NaN,Released,NaN,The Tempest,NaN,0.0
21854,None,NaN,Drama|Science Fiction|Animation,152795.0,en,More than two decades after catapulting to sta...,8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,Pandora Filmproduktion|Entre Chien et Loup|Opu...,Belgium|France|Germany|Israel|Luxembourg|Poland,2013-05-16,0.455815,122.0,English,Released,NaN,The Congress,6.4,165.0
22151,None,NaN,Action|Horror|Science Fiction,18440.0,en,When a comet strikes Earth and kicks up a clou...,1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,NaN,United States of America,2007-01-01,NaN,89.0,English,Released,NaN,Days of Darkness,5.0,5.0
23044,None,NaN,Drama,25541.0,da,Former Danish servicemen Lars and Jimmy are th...,2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,NaN,Sweden|Denmark,2009-10-21,NaN,90.0,Dansk,Released,NaN,Brotherhood,7.1,21.0
24844,None,NaN,Comedy|Drama,11115.0,en,As an ex-gambler teaches a hot-shot college ki...,6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,Andertainment Group|Crescent City Pictures|Tag...,United States of America,2008-01-29,NaN,85.0,English,Released,NaN,Deal,5.2,22.0
28860,None,NaN,Drama|Comedy,168538.0,en,"In Zola's Paris, an ingenue arrives at a tony ...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,Cannon Group|Metro-Goldwyn-Mayer (MGM),NaN,1983-06-13,NaN,92.0,NaN,Released,NaN,"Nana, the True Key of Pleasure",4.7,3.0
29374,None,NaN,Drama|Foreign,42495.0,en,"King Lear, old and tired, divides his kingdom ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,Royal Shakespeare Company|Laterna Film|Athena ...,Denmark|United Kingdom,1971-02-04,NaN,137.0,English,Rumored,NaN,King Lear,8.0,3.0
35798,Why We Fight,NaN,Documentary,159849.0,en,"The third film of Frank Capra's 'Why We Fight""...",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,NaN,United States of America,1943-01-01,NaN,57.0,English,Released,NaN,Why We Fight: Divide and Conquer,5.0,1.0
38871,None,NaN,Action|Drama|Romance|Adventure,99080.0,en,"Originally called White Thunder, American prod...",0.002362,/qenjwRvW9itR5pVp4CBkYfhVAOp.jpg,NaN,NaN,1931-06-21,NaN,70.0,English,Released,Actually produced during the Great Newfoundlan...,The Viking,NaN,0.0
40040,None,0.98,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm...",United Kingdom|United States of America|France...,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0
40276,None,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstit...",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
45265,None,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,1.359497,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0

In [142]:
df = df.drop_duplicates()

In [143]:
df.duplicated().sum()

np.int64(0)

## Handling Missing Values & Removing Observations

17. __Drop__ all rows/movies with unknown __id__ or __title__.

In [144]:
df[['id', 'title']].isna().sum()

id       3
title    6
dtype: int64

In [145]:
df = df.dropna(subset=['id', 'title'])

In [146]:
df[['id', 'title']].isna().sum()

id       0
title    0
dtype: int64

In [147]:
df['id'] = pd.to_numeric(df['id'], errors='coerce')
df = df.dropna(subset=['id', 'title'])

In [148]:
df[['id', 'title']].isna().sum()

id       0
title    0
dtype: int64

18. __Keep__ only those rows/movies in the df with __10 or more non-NaN__ values.

In [149]:
df = df[df.isna().sum(axis=1) <10]

In [150]:
df.isna().sum(axis = 1)

0        1
1        1
2        2
3        1
4        1
        ..
45461    5
45462    5
45463    3
45464    7
45465    7
Length: 45126, dtype: int64

## Final (Cleaning) Steps

19. __Keep__ only those rows/movies in the df with __status "Released"__. Then __drop__ the column "status".

In [151]:
df = df[df['status']=="Released"]

In [152]:
df = df.drop('status', axis=1)

In [153]:
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'tagline', 'title', 'vote_average', 'vote_count'],
      dtype='object')

20. The Order of the columns should be as follows:

In [157]:

["id", "title", "tagline", "release_date", "genres",
     "belongs_to_collection", "original_language",
     "budget", "revenue", "production_companies",
     "production_countries", "vote_count", "vote_average",
     "popularity", "runtime", "overview",
     "spoken_languages", "poster_path"]

['id',
 'title',
 'tagline',
 'release_date',
 'genres',
 'belongs_to_collection',
 'original_language',
 'budget',
 'revenue',
 'production_companies',
 'production_countries',
 'vote_count',
 'vote_average',
 'popularity',
 'runtime',
 'overview',
 'spoken_languages',
 'poster_path']

In [158]:
df = df[
    ["id", "title", "tagline", "release_date", "genres",
     "belongs_to_collection", "original_language",
     "budget", "revenue", "production_companies",
     "production_countries", "vote_count", "vote_average",
     "popularity", "runtime", "overview",
     "spoken_languages", "poster_path"]
]

In [159]:
df.columns

Index(['id', 'title', 'tagline', 'release_date', 'genres',
       'belongs_to_collection', 'original_language', 'budget', 'revenue',
       'production_companies', 'production_countries', 'vote_count',
       'vote_average', 'popularity', 'runtime', 'overview', 'spoken_languages',
       'poster_path'],
      dtype='object')

21. __Reset__ the Index and create a __RangeIndex__.

In [160]:
df = df.reset_index(drop=True)

In [161]:
df

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget,revenue,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,862.0,Toy Story,NaN,1995-10-30,Animation|Comedy|Family,Toy Story Collection,en,30.0,373.554033,Pixar Animation Studios,United States of America,5415.0,7.7,21.946943,81.0,"Led by Woody, Andy's toys live happily in his ...",English,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,8844.0,Jumanji,Roll the dice and unleash the excitement!,1995-12-15,Adventure|Fantasy|Family,None,en,65.0,262.797249,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,2413.0,6.9,17.015539,104.0,When siblings Judy and Peter discover an encha...,English|Français,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,15602.0,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,en,NaN,NaN,Warner Bros.|Lancaster Gate,United States of America,92.0,6.5,11.712900,101.0,A family wedding reignites the ancient feud be...,English,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,31357.0,Waiting to Exhale,Friends are the people who let you be yourself...,1995-12-22,Comedy|Drama|Romance,None,en,16.0,81.452156,Twentieth Century Fox Film Corporation,United States of America,34.0,6.1,3.859495,127.0,"Cheated on, mistreated and stepped on, the wom...",English,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,11862.0,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,1995-02-10,Comedy,Father of the Bride Collection,en,NaN,76.578911,Sandollar Productions|Touchstone Pictures,United States of America,173.0,5.7,8.387519,106.0,Just when George Banks has recovered from his ...,English,/e64sOI48hQXyru7naBFyssKFxVd.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44695,439050.0,Subdue,Rising and falling between a man and woman,NaT,Drama|Family,None,fa,NaN,NaN,NaN,Iran,1.0,4.0,0.072051,90.0,Rising and falling between a man and woman.,فارسی,/jldsYflnId4tTWPx8es3uzsB1I8.jpg
44696,111109.0,Century of Birthing,NaN,2011-11-17,Drama,None,tl,NaN,NaN,Sine Olivia,Philippines,3.0,9.0,0.178241,360.0,An artist struggles to finish his work while a...,NaN,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
44697,67758.0,Betrayal,A deadly game of wits.,2003-08-01,Action|Drama|Thriller,None,en,NaN,NaN,American World Pictures,United States of America,6.0,3.8,0.903007,90.0,"When one of her hits goes wrong, a professiona...",English,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
44698,227506.0,Satan Triumphant,NaN,1917-10-21,NaN,None,en,NaN,NaN,Yermoliev,Russia,0.0,NaN,0.003503,87.0,"In a small town live two brothers, one a minis...",NaN,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
44699,461257.0,Queerama,NaN,2017-06-09,NaN,None,en,NaN,NaN,NaN,United Kingdom,0.0,NaN,0.163015,75.0,50 years after decriminalisation of homosexual...,English,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg

22. __Save__ the cleaned dataset in a __csv-file__.

In [162]:
df.to_csv("cleaned_movies.csv", index=False)